### ISSUE TITLE
Archiving is stucked on Xcode 11 beta 3

### ISSUE THREAD

**Issue by Igor-Palaguta** [scinfu/SwiftSoup#116]
In new Xcode 11 beta 3 carthage is stucked during building SwiftSoup. Same effect when archiving directly from Xcode

Some issue during optimizations. After disable optimizations for release everything works
```
SWIFT_OPTIMIZATION_LEVEL = -Onone
```

**Comment by 7ukasz** [comment]
I'am experiencing a similar problem on Xcode 11 Beta 3 but with CocoaPods. The build is stucked on building SwiftSoup. Adjusting `SWIFT_OPTIMIZATION_LEVEL` did not help.

**Comment by YaoXiaochuan** [comment]
It is also stucked in Xcode 11 beta 4

**Comment by rectangular** [comment]
And beta 5!

**Comment by funkenstrahlen** [comment]
Have you all reported this bug to Apple? This definitely needs to get fixed on their side.

**Comment by funkenstrahlen** [comment]
Still not fixed in Xcode beta 6.

**Comment by imWildCat** [comment]
I reported it again just now.

**Comment by Dschee** [comment]
Hey everyone, while it's not a real fix, as noted by @Igor-Palaguta a workaround is to set the `SWIFT_OPTIMIZATION_LEVEL` to `-Onone` for release builds. I've done exactly that in my fork, feel free to use it's "master@ branch instead of this original repo when installing via Carthage or Accio. Unfortunately, they seem not want to merge it, as can be seen by my PR https://github.com/scinfu/SwiftSoup/pull/117.

In Accio, use this entry instead:

```swift
.package(url: "https://github.com/Dschee/SwiftSoup.git", .branch("master")),
```

In Carthage, use that:

```OGDL
github "Dschee/SwiftSoup" "master"
```

**Comment by funkenstrahlen** [comment]
Awesome! Do you know when this might be part of Xcode officially?

**Comment by kylebrowning** [comment]
It's still not in the master snapstshot for 5.1

**Comment by imWildCat** [comment]
It looks like this issue is not fixed in Xcode 11 GM released today?

**Comment by nicolas-miari** [comment]
I can manually change the optimization levels on my local machine (everytime carthage checks out the sources, and before building), but I also have continuous integration set up on a server, not sure how I could apply the workaround there. 

I wonder what is so special in the SwiftSoup source code that triggers the issue... Isn't there a way to work around this at the source code level until Apple fixes the issue on their end?  I have several other dependencies, but none of them suffer of anything similar...

**Comment by funkenstrahlen** [comment]
It does compile with the latest swift trunk snapshot: https://swift.org/download/#snapshots

However Apple does not allow submitting builds to the App Store that are not compiled with the Xcode default toolchain.

So I just disabled optimization as described here and can live with this for now.

**Comment by scinfu** [comment]
I merged @Dschee PR with  SWIFT_OPTIMIZATION_LEVEL to -Onone.
Can someone confirm is fixed? I do not use Carthage.
Thank you

**Comment by kkla320** [comment]
Using Xcode 11 GM and SwiftSoup with the PR from @Dschee doesn't work for me. The build is still stuck.

**Comment by catluc** [comment]
Same for me  @kkla320, your merge @scinfu still doesnt work in last XCode 11 GM with Carthage, same error since Xcode 11 beta 3!!

**Comment by funkenstrahlen** [comment]
@catluc Please do not be too aggressive. This is an Swift Compiler bug and you should be angry with Apple not shipping the fix in Xcode GM.

**Comment by kylebrowning** [comment]
It’ll be fixed When swift 5.1 drops is my guess

**Comment by catluc** [comment]
@funkenstrahlen I am still not seeing were is the agressive part, @scinfu  was asking for feedback in previous comment, and i gave him that feedback, I am very aware that Apple needs to fix their bugs.

**Comment by lawgimenez** [comment]
So, this is the culprit. I can't release my build because of this bug.

**Comment by kylebrowning** [comment]
I know not everyone will be able to do this, but we just removed SwiftSoup and moved on with our lives.

**Comment by mikeycoder123** [comment]
> Same for me @kkla320, your merge @scinfu still doesnt work in last XCode 11 GM with Carthage, same error since Xcode 11 beta 3!!

The same thing is happening to me in Xcode 11 GM 2. This must be fixed soon, either by Apple (if it's their end) or the developers of Swift Soup (if it's their end).

**Comment by nicolas-miari** [comment]
> I know not everyone will be able to do this, but we just removed SwiftSoup and moved on with our lives.

I'm about to do the same. My app only uses SwiftSoup to retrieve a single URL from the src attribute of an &lt;a href&gt; tag within a **bloated** HTML document with huge commented-out sections and even those IE hacks from the 00's in place. The guy who first develped my app seems to think dependencies are some sort of magic wand, free of consequences and hassles, use as many as you want. 

I asked my server-side team to provide a dedictaed API that just gives me the URL straight; should be ready any time now. 

**SwiftSoup is a great framework** for people who really need it. But personally, I believe using HTML and web views in a native app is an abomination, a necessary evil at best.

**Comment by lawgimenez** [comment]
Removed this framework and was able to publish on TestFlight. I migrated to another framework that works.

**Comment by tomxu2k** [comment]
> 
> 
> Removed this framework and was able to publish on TestFlight. I migrated to another framework that works.
Would you please teach me the name of framework you migrated?

**Comment by scinfu** [comment]
Thank you to @kkla320 for PR.
Now seem  fixed also in my test.

Feel free  to reopen this issue if bug persits.

**Comment by WillBishop** [comment]
I still not able to get it to build. It still hangs during the archive.

**Comment by scinfu** [comment]
Hi
i added new version 2.2.1.
Previously made fixes were not included in a version.
Let me find out if the problem persists

**Comment by imWildCat** [comment]
According to my observation, this issue has been addressed in Xcode 11.2 (11B52).

cc @scinfu @gottesmm
